trigger:
  - feature/as-3074-appeal-service-api-pipeline
  - subtask/as-3238-add-horizon-azure-function

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  tag: '$(Build.BuildId)'
  appealsApiDockerfilePath: '$(Build.SourcesDirectory)/packages/appeals-service-api/Dockerfile'
  documentServiceApiDockerfilePath: '$(Build.SourcesDirectory)/packages/document-service-api/Dockerfile'
  appealsReplyApiDockerfilePath: '$(Build.SourcesDirectory)/packages/appeal-reply-service-api/Dockerfile'
  pdfServiceApiDockerfilePath: '$(Build.SourcesDirectory)/packages/pdf-service-api/Dockerfile'
  formswebappServiceApiDockerfilePath: '$(Build.SourcesDirectory)/packages/forms-web-app/Dockerfile'
  lpaServiceApiDockerfilePath: '$(Build.SourcesDirectory)/packages/lpa-questionnaire-web-app/Dockerfile'
  commonsDockerfilePath: '$(Build.SourcesDirectory)/packages/common/Dockerfile' 
  imageRepository: 'planninginspectorateappealplanningdecision'
  containerRegistry: 'pinscommonukscontainers3887default.azurecr.io'
  dockerRegistryServiceConnection: 'appeals-service-api-registry-connection'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:                                                     
  - stage: Build_Horizon_Functions
    displayName: Build and Deploy Horizon Functions
    jobs:
      - job: BuildHorizonHouseholderAppealPublish
        pool:
          vmImage: $(vmImageName)
        displayName: Build Horizon Householder Appeal Publish Function
        steps:
          - bash: |
              cd packages/horizon-householder-appeal-publish
              npm install 
              npm run build --if-present
              npm prune --production
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/packages/horizon-householder-appeal-publish"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip'
              artifactName: 'horizon-householder-appeal-publish-artifact'
      - job: BuildHorizonCreateContactFunction
        pool:
          vmImage: $(vmImageName)
        displayName: Build Horizon Create Contact Function
        steps:
          - bash: |
              cd packages/horizon-create-contact
              npm install 
              npm run build --if-present
              npm prune --production
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/packages/horizon-create-contact"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip'
              artifactName: 'horizon-create-contact-artifact'
      - job: BuildHorizonAddContactFunction
        pool:
          vmImage: $(vmImageName)
        displayName: Build Horizon Add Contact Function
        steps:
          - bash: |
              cd packages/horizon-add-document
              npm install 
              npm run build --if-present
              npm prune --production
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/packages/horizon-add-document"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip'
              artifactName: 'horizon-add-document-artifact'
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'PINS ODTDEV (38602df9-8f79-41d1-a971-50c7672ba6f1)'
              appType: functionAppLinux
              appName: 'horizon-poc'
              package: $(System.DefaultWorkingDirectory)/build/$(Build.BuildId).zip
              startUpCommand: node handler.js
              deploymentMethod: zipDeploy
        




  